INSERT INTO orderuser.ORDERS VALUES (orderuser.ORDER_SEQ.NEXTVAL, 'John Doe', TRUNC(SYSDATE), 1500.00, 'COMPLETED', SYSTIMESTAMP);
INSERT INTO orderuser.ORDERS VALUES (orderuser.ORDER_SEQ.NEXTVAL, 'Jane Smith', TRUNC(SYSDATE), 2300.50, 'PENDING', SYSTIMESTAMP);
INSERT INTO orderuser.ORDERS VALUES (orderuser.ORDER_SEQ.NEXTVAL, 'Bob Johnson', TRUNC(SYSDATE), 890.75, 'SHIPPED', SYSTIMESTAMP);
INSERT INTO orderuser.ORDERS VALUES (orderuser.ORDER_SEQ.NEXTVAL, 'Alice Brown', TRUNC(SYSDATE), 3400.00, 'COMPLETED', SYSTIMESTAMP);
INSERT INTO orderuser.ORDERS VALUES (orderuser.ORDER_SEQ.NEXTVAL, 'Charlie Wilson', TRUNC(SYSDATE), 1200.00, 'PENDING', SYSTIMESTAMP);
