-- Create user and grant privileges (requires application to connect as a privileged user like 'system')
CREATE USER orderuser IDENTIFIED BY orderpass;
GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE SEQUENCE TO orderuser;
ALTER USER orderuser QUOTA UNLIMITED ON USERS;

CREATE SEQUENCE orderuser.ORDER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE orderuser.ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    TOTAL_AMOUNT NUMBER(10, 2) NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
