spring.application.name=order-service
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=false

server.port=8081

logging.level.root=INFO
logging.level.com.orders=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
